### ISSUE TITLE
add a command to find package dependencies that should be in dev_dependencies

### ISSUE THREAD

**Issue by devoncarew** [google/tuneup.dart#10]

**Comment by zoechi** [comment]
Why did you close it? Not planned? I think there was a similar request for the linter package.

**Comment by devoncarew** [comment]
Yeah, effectively not planned or not likely. It would be nice to have but its not likely that I will have time to work on it.

**Comment by travissanderson-wf** [comment]
linter feature request is here https://github.com/dart-lang/linter/issues/30
