### ISSUE TITLE
add a --watch mode?

### ISSUE THREAD

**Issue by devoncarew** [google/tuneup.dart#16]
Add a `--watch` mode to tuneup? This would:
- be a long lived process
- print out all errors on startup
- watch for file system changes
- print out the diff of errors as files change. So, error 'foo' fixed, error 'bar' added

This would be a useful mode for people that didn't have analysis integration into their IDE.

**Comment by seaneagan** [comment]
Could this possibly be a feature of the analysis server:

https://pub.dartlang.org/packages/analysis_server

(once it's published)

**Comment by devoncarew** [comment]
I think technically it could, but I'm not sure that it's likely too. Currently they use stdio for the traffic between the host IDE and the analysis server.

My idea with this was to support clients that didn't have any real dart integration, analysis server or otherwise. Specifically, I was experimenting with using cloud 9 to develop Dart apps. It's pretty capable from a git / CLI / code editing perspective, but doesn't have any dart analysis smarts. My idea was to run `tuneup --watch` from a console tab, and then it would print out to stdout when you introduced a new error, or fixed an existing one. Sort of a poor man's problem view.

**Comment by devoncarew** [comment]
not planned :(
