### ISSUE TITLE
Check command will miss some analysis errors in part files

### ISSUE THREAD

**Issue by danschultz** [google/tuneup.dart#32]
I'm using the `check` command, and it misses analysis errors for Dart files that are included in a library via `part` `part of`.

**Comment by devoncarew** [comment]
It should be analyzing every source file in the project - part or not - in the `lib/`, `bin/`, `test/`, ... dirs. Can you make a small repo case, or point me to a repository with the issue?

**Comment by danschultz** [comment]
> Can you make a small repo case, or point me to a repository with the issue?

Sure. Seems like that the analyzer hasn't finished analyzing by the time `context.getErrors` is called, and/or `context.computeErrors` isn't forcing analysis.

Putting the following code before `computeErrors` is called fixes the problem, at least in my small project.

```dart
var result = context.performAnalysisTask();
while (result.hasMoreWork) {
  print("theres more work");
  result = context.performAnalysisTask();
}
```

This probably isn't an ideal workaround for larger projects.

**Comment by danschultz** [comment]
@devoncarew here's the [repo](https://github.com/danschultz/tuneup_check_bug_repro) where you can reproduce the bug.

**Comment by devoncarew** [comment]
Thanks for the repo and fix! I'll push a new version now.

**Comment by danschultz** [comment]
Thanks @devoncarew!
