### ISSUE TITLE
Tuneup shows unused imports (info) while dartanalyzer doesn't

### ISSUE THREAD

**Issue by zoechi** [google/tuneup.dart#41]
The unused imports are worked around by using Dartdoc comments
For example this line https://github.com/bwu-dart/bwu_bind_html/blob/611a99c0c79c3fd3d367675ee308fec619c7b5b5/test/bwu_bind_html_test.dart#L11
and the comment two lines below

**Comment by devoncarew** [comment]
Should be fixed by the `0.3.0` version.
