### ISSUE TITLE
Specify witch files to analyze

### ISSUE THREAD

**Issue by long1eu** [google/tuneup.dart#77]
I try to exclude generated files. Since the analysis_option, clearly doesn't work https://github.com/dart-lang/sdk/issues/25551, is there a way to specify here what files to analyze?

**Comment by devoncarew** [comment]
It does work for tuneup - this tool is backed by the analysis server, not the dart analyzer.

You can specify excludes via https://dart.dev/guides/language/analysis-options#excluding-code-from-analysis .
